version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shiot_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - mqtt
  db:
    image: postgres:15
    container_name: shiot_db
    restart: always
    environment:
      POSTGRES_USER: ${}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  mqtt:
    image: eclipse-mosquitto:2
    container_name: shiot_mqtt
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_config:/mosquitto/config
volumes:
  db_data:
  mosquitto_data:
  mosquitto_config:
